// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA02kyVeUbda0Dc6Ur4OlDPk3BZkLd8FLU',
    appId: '1:329450180034:web:b0a9bb5fe4aff14da09a5b',
    messagingSenderId: '329450180034',
    projectId: 'mate-order-dbfd2',
    authDomain: 'mate-order-dbfd2.firebaseapp.com',
    storageBucket: 'mate-order-dbfd2.firebasestorage.app',
    measurementId: 'G-LTV8D6J11C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoXlzu0K-KpYPGwusdUVtsN_rpsxPbgEw',
    appId: '1:329450180034:android:7f5bb4a47de1b4c3a09a5b',
    messagingSenderId: '329450180034',
    projectId: 'mate-order-dbfd2',
    storageBucket: 'mate-order-dbfd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZeuuaaMVIwViz_sHLHQ2LWHh3zIXW97o',
    appId: '1:329450180034:ios:f2f286c9ec9e97c0a09a5b',
    messagingSenderId: '329450180034',
    projectId: 'mate-order-dbfd2',
    storageBucket: 'mate-order-dbfd2.firebasestorage.app',
    iosBundleId: 'com.example.mateOrderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA02kyVeUbda0Dc6Ur4OlDPk3BZkLd8FLU',
    appId: '1:329450180034:web:bb288312aa06bf52a09a5b',
    messagingSenderId: '329450180034',
    projectId: 'mate-order-dbfd2',
    authDomain: 'mate-order-dbfd2.firebaseapp.com',
    storageBucket: 'mate-order-dbfd2.firebasestorage.app',
    measurementId: 'G-C6N8VJK4DH',
  );
}
